language: node_js
node_js:
- '8.9'
branches:
  only:
  - master
before_script:
- yarn global add @angular/cli
script:
- yarn build

notifications:
  email:
    on_failure: change
    on_success: change
